name: 'Unity Log Parser'
description: 'Parse Unity Editor log files and generate workflow annotations'
inputs:
  log-path:
    description: 'Path to the Unity Editor log file'
    required: true

outputs:
  error-count:
    description: 'Total number of errors found in the log file'

runs:
  using: "composite"
  steps:
    - name: Run Unity log parser
      id: parse-log
      run: ./.github/actions/unity-log-parser-action/unity-log-parser.sh ${{ inputs.log-path }}
      shell: bash