name: 'Unity Log Parser'
description: 'Parse Unity Editor log files and generate workflow annotations'
inputs:
  log-path:
    description: 'Path to the Unity Editor log file'
    required: true

outputs:
  errors:
    description: 'Errors found in the log file'

runs:
  using: "composite"
  steps:
    - name: Run Unity log parser
      run: python .github/actions/unity-log-parser-action/unity-log-parser.py '${{ inputs.log-path }}'
      shell: bash

    - name: Capture errors output
      run: echo "errors=$(cat errors_output.txt)" >> $GITHUB_OUTPUT
      shell: bash